[package]
name = "mandelbrot"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.1.11", features = ["derive"] }
image = "0.25.5"
indicatif = "0.17.3"
num = "0.4.0"
rayon = "1.7.0"
rand = "0.9.0"
